# frozen_string_literal: true

module Foaf
  module Trustline
    module Protocol
      # Fee calculation for trustline transfers.
      # Mirrors CurrencyNetworkBasic._calculateFees and related functions.
      # No Rails, no I/O, no database.
      #
      # Phase 1: capacity_imbalance_fee_divisor is 0 (disabled), so all fees are zero.
      # The full calculation is implemented so it activates when parameters change.
      #
      # Fee model (from Trustlines):
      #   Intermediaries in a multi-hop transfer charge fees based on the
      #   imbalance their trustline experiences. The fee compensates for the
      #   capacity reduction caused by routing through them.
      #
      #   fee = ceil(imbalance_generated / capacity_imbalance_fee_divisor)
      #
      #   When divisor is 0, fees are disabled (Phase 1).
      module FeeCalculator
        module_function

        # Calculate fees for a forward transfer (receiver-pays mode).
        # Mirrors CurrencyNetworkBasic._calculateFees
        #
        # @param imbalance_generated [BigDecimal] imbalance caused by the transfer
        # @param capacity_imbalance_fee_divisor [Integer] fee divisor (0 = no fees)
        # @return [BigDecimal] fee amount
        def calculate_fees(imbalance_generated:, capacity_imbalance_fee_divisor:)
          return BigDecimal("0") if capacity_imbalance_fee_divisor == 0 || imbalance_generated <= 0

          # Ceiling division: (imbalance - 1) / divisor + 1
          ((imbalance_generated - 1) / capacity_imbalance_fee_divisor) + 1
        end

        # Calculate fees in reverse (sender-pays mode).
        # Used when walking a path backwards to accumulate fees.
        # Mirrors CurrencyNetworkBasic._calculateFeesReverse
        #
        # @param imbalance_generated [BigDecimal] imbalance caused by the transfer
        # @param capacity_imbalance_fee_divisor [Integer] fee divisor (0 = no fees)
        # @return [BigDecimal] fee amount
        def calculate_fees_reverse(imbalance_generated:, capacity_imbalance_fee_divisor:)
          return BigDecimal("0") if capacity_imbalance_fee_divisor == 0 || imbalance_generated <= 0

          # Reverse formula: ceil(imbalance / (divisor - 1))
          # (imbalance - 1) / (divisor - 1) + 1
          ((imbalance_generated - 1) / (capacity_imbalance_fee_divisor - 1)) + 1
        end

        # Calculate the imbalance generated by a transfer on a trustline.
        # Mirrors CurrencyNetworkBasic._calculateImbalanceGenerated
        #
        # If balance > 0 (receiver owes sender), the transfer first reduces
        # existing debt before creating new imbalance. Only the portion
        # beyond the existing balance creates imbalance.
        #
        # @param value [BigDecimal] transfer amount
        # @param balance [BigDecimal] current balance from sender's perspective
        # @return [BigDecimal] imbalance generated (always >= 0)
        def imbalance_generated(value:, balance:)
          if balance <= 0
            # Sender already owes receiver, full value creates imbalance
            value
          else
            # Receiver owes sender — transfer reduces debt first
            [value - balance, BigDecimal("0")].max
          end
        end

        # Calculate total fees for a path in sender-pays mode.
        # Walks the path backwards (receiver to sender), accumulating fees.
        #
        # @param path_balances [Array<Hash>] each element: { balance:, creditline_received: }
        #   ordered from sender to receiver (same as path order)
        # @param value [BigDecimal] amount the receiver should get
        # @param capacity_imbalance_fee_divisor [Integer] fee divisor
        # @param max_fee [BigDecimal] maximum acceptable total fee
        # @return [Hash] { fees:, forwarded_values: [...] } or raises MaxFeeExceeded
        def calculate_path_fees_sender_pays(path_balances:, value:, capacity_imbalance_fee_divisor:, max_fee:)
          return { fees: BigDecimal("0"), forwarded_values: Array.new(path_balances.size, value) } if capacity_imbalance_fee_divisor == 0

          total_fees = BigDecimal("0")
          forwarded_value = value
          forwarded_values = []

          # Walk backwards through the path (receiver to sender)
          path_balances.reverse.each_with_index do |hop, reverse_index|
            if reverse_index == 0
              # Receiver pays no fee
              forwarded_values.unshift(forwarded_value)
              next
            end

            imbalance = imbalance_generated(value: forwarded_value, balance: hop[:balance])
            fee = calculate_fees_reverse(
              imbalance_generated: imbalance,
              capacity_imbalance_fee_divisor: capacity_imbalance_fee_divisor
            )

            forwarded_value += fee
            total_fees += fee

            raise MaxFeeExceeded.new(total_fees: total_fees, max_fee: max_fee) if total_fees > max_fee

            forwarded_values.unshift(forwarded_value)
          end

          { fees: total_fees, forwarded_values: forwarded_values }
        end

        # Calculate total fees for a path in receiver-pays mode.
        # Walks the path forwards (sender to receiver), subtracting fees.
        #
        # @param path_balances [Array<Hash>] each element: { balance:, creditline_received: }
        # @param value [BigDecimal] amount the sender sends
        # @param capacity_imbalance_fee_divisor [Integer] fee divisor
        # @param max_fee [BigDecimal] maximum acceptable total fee
        # @return [Hash] { fees:, forwarded_values: [...] } or raises MaxFeeExceeded
        def calculate_path_fees_receiver_pays(path_balances:, value:, capacity_imbalance_fee_divisor:, max_fee:)
          return { fees: BigDecimal("0"), forwarded_values: Array.new(path_balances.size, value) } if capacity_imbalance_fee_divisor == 0

          total_fees = BigDecimal("0")
          forwarded_value = value
          forwarded_values = []

          path_balances.each_with_index do |hop, index|
            forwarded_values << forwarded_value

            # Last hop (receiver) pays no fee
            next if index == path_balances.size - 1

            imbalance = imbalance_generated(value: forwarded_value, balance: hop[:balance])
            fee = calculate_fees(
              imbalance_generated: imbalance,
              capacity_imbalance_fee_divisor: capacity_imbalance_fee_divisor
            )

            forwarded_value -= fee
            total_fees += fee

            raise MaxFeeExceeded.new(total_fees: total_fees, max_fee: max_fee) if total_fees > max_fee
          end

          { fees: total_fees, forwarded_values: forwarded_values }
        end
      end

      # Raised when total fees on a path exceed the caller's max_fee parameter.
      class MaxFeeExceeded < StandardError
        attr_reader :total_fees, :max_fee

        def initialize(total_fees:, max_fee:)
          @total_fees = total_fees
          @max_fee = max_fee
          super("Fees #{total_fees} exceed maximum #{max_fee}")
        end
      end
    end
  end
end
